### ISSUE TITLE
redis description wrong (kafka instead of redis)

### ISSUE THREAD

**Issue by pcornelissen** [jnylen/rancher-catalog#1]
I just notices that the readme.md for redis is wrong:

`This template creates, scale in and scale out a multinodes broker (kafka) cluster on top of Rancher. The configuration is generated with confd from Rancher metadata. Cluster size are variable after deployment, and get reconfigured if refresh interval > 0.
`

I guess you meant redis not Kafka

**Comment by jnylen** [comment]
Hi @pcornelissen,
I'll fix it when i'm updating some other catalog items.

Thanks for reporting!
